export const POSTHOG_EVENTS = {
  landingView: "landing_view",
  waitlistCtaClick: "waitlist_cta_click",
  cookieConsentUpdated: "cookie_consent_updated",
  signupCompleted: "signup_completed",
  loginCompleted: "login_completed",
  matchViewed: "match_viewed",
  matchTabChanged: "match_tab_changed",
  matchFormScopeChanged: "match_form_scope_changed",
  matchH2hScopeChanged: "match_h2h_scope_changed",
  matchMomentumViewed: "match_momentum_viewed",
  aiInsightGenerated: "ai_insight_generated",
  aiLimitReached: "ai_limit_reached",
  aiGenerateClicked: "ai_generate_clicked",
  teamViewed: "team_viewed",
  playerViewed: "player_viewed",
  leagueViewed: "league_viewed",
  aiLiveInsightViewed: "ai_live_insight_viewed",
  aiLiveInsightUnavailable: "ai_live_insight_unavailable",
  matchScoreFlipped: "match_score_flipped",
  liveMeaningfulEventReceived: "live_meaningful_event_received",
  liveCenterAiUpdatedMarkerRendered: "live_center_ai_updated_marker_rendered",
  followAdded: "follow_added",
  followRemoved: "follow_removed",
  favoriteAdded: "favorite_added",
  favoriteRemoved: "favorite_removed",
  trialStarted: "trial_started",
  trialConverted: "trial_converted",
  subscriptionCancelled: "subscription_cancelled",
  predictionsCenterViewed: "predictions_center_viewed",
} as const;

export type PostHogEventName =
  (typeof POSTHOG_EVENTS)[keyof typeof POSTHOG_EVENTS];
